package core.menu_object;

public enum MenuButtonType
{
	HOST_GAME,
	JOIN_GAME,
	CONNECT_TO_IP,
	CONTINUE_TO_GAME,
	SELECT_MAP,
	BACK_TO_MENU,
	LEVEL_EDITOR,
	REFRESH_LAN_SERVERS,
	INFO_BUTTON,
	SETTINGS_BUTTON,
	PLAYER_SELECT;
}
